name: Check file size
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 1073741824  # 1GB
