name: Check file size and sync to Google Drive
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 1073741824  # 1GB

  convert-and-sync:
    runs-on: ubuntu-latest
    needs: check-file-size
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Pull LFS files
        run: |
          git lfs install
          git lfs pull

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup system dependencies
        run: chmod +x .github/workflows/scripts/setup_system.sh && .github/workflows/scripts/setup_system.sh

      - name: Convert MD to PDF
        run: chmod +x .github/workflows/scripts/convert_md_to_pdf.sh && .github/workflows/scripts/convert_md_to_pdf.sh
      
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdfs
          path: "**/*.pdf"
          retention-days: 30

      - name: Upload to Google Drive
        env:
          GOOGLE_OAUTH_TOKEN: ${{ secrets.GOOGLE_OAUTH_TOKEN }}
        run: python .github/workflows/scripts/upload_to_drive.py