name: Sync to Hugging Face hub and Google Drive
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub-and-drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull LFS files
        run: |
          git lfs install
          git lfs pull

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup system dependencies
        run: chmod +x .github/workflows/scripts/setup_system.sh && .github/workflows/scripts/setup_system.sh

      - name: Convert MD to PDF
        run: chmod +x .github/workflows/scripts/convert_md_to_pdf.sh && .github/workflows/scripts/convert_md_to_pdf.sh
      
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdfs
          path: "**/*.pdf"
          retention-days: 30

      - name: Upload to Google Drive
        env:
          # Primary authentication method (OAuth)
          GOOGLE_OAUTH_TOKEN: ${{ secrets.GOOGLE_OAUTH_TOKEN }}
          # Fallback authentication method (Service Account)
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: python .github/workflows/scripts/upload_to_drive.py

      - name: Push to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push --force https://prathameshv07:$HF_TOKEN@huggingface.co/spaces/prathameshv07/Multilingual-Audio-Intelligence-System main